site:
  title: Hazelcast Guides
  url: https://guides.hazelcast.org
  start_page: home::index.adoc
  keys:
    google_analytics: 'UA-3921306-4'
urls:
  html_extension_style: indexify
content:
  branches: master # ignore "v*" branches.
  sources:
    - url: . # home
      branches: HEAD
      start_path: home
    - url: https://github.com/hazelcast-guides/adoc-templates.git
      branches: antora-doc
    - url: https://github.com/hazelcast-guides/hazelcast-embedded-springboot
      start_path: doc
    - url: https://github.com/hazelcast-guides/springboot-hibernate
      start_path: doc
    - url: https://github.com/hazelcast-guides/hibernate-jcache
      start_path: doc
    - url: https://github.com/hazelcast-guides/istio
      start_path: doc
    - url: https://github.com/hazelcast-guides/caching-micronaut
      start_path: doc
    - url: https://github.com/hazelcast-guides/kubernetes-embedded
      start_path: doc
    - url: https://github.com/hazelcast-guides/hazelcast-embedded-microprofile
      start_path: doc
    - url: https://github.com/hazelcast-guides/hazelcast-client-quarkus
      start_path: doc
    - url: https://github.com/hazelcast-guides/springboot-webfilter-session-replication
      start_path: doc
    - url: https://github.com/hazelcast-guides/caching-springboot
      start_path: doc
    - url: https://github.com/hazelcast-guides/ecs-embedded
      start_path: doc
    - url: https://github.com/hazelcast-guides/striim-cdc
      start_path: doc
    - url: https://github.com/hazelcast-guides/caching-springboot-jcache
      start_path: doc
    - url: https://github.com/hazelcast-guides/springboot-tomcat-session-replication
      start_path: doc
    - url: https://github.com/hazelcast-guides/vmware-tanzu
      start_path: doc
    - url: https://github.com/hazelcast-guides/terraform-quickstarts
      start_path: doc
asciidoc:
  extensions:
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://github.com/hazelcast-guides/guides-ui/releases/download/v13/ui-bundle.zip
    snapshot: true
